# Generated by Django 2.1.3 on 2019-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
