# Generated by Django 2.1.3 on 2019-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='extra_curricular',
        ),
        migrations.AddField(
            model_name='student',
            name='datePermission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
